name: Build and Push Docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Output Environment Variables
        run: printenv

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Debug Docker Info
        run: docker info

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push app image
        run: |
          docker build -t myapp:latest -f Dockerfile .
          docker tag myapp:latest 808973727775.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
          docker push 808973727775.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push db image
        run: |
          docker build -t mydb:latest -f Dockerfile.db .
          docker tag mydb:latest 808973727775.dkr.ecr.us-east-1.amazonaws.com/mydb:latest
          docker push 808973727775.dkr.ecr.us-east-1.amazonaws.com/mydb:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


